# Generated by Django 3.0.8 on 2020-07-31 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eventtools.models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_type', models.CharField(choices=[('Compost', 'Compost'), ('Landfill', 'Landfill'), ('Wood', 'Wood'), ('Metal', 'Metal'), ('Paper/Cardboard', 'Paper/Cardboard'), ('Plastic Wrap', 'Plastic Wrap'), ('Plastic Bottles/Containers', 'Plastic Bottles/Containers'), ('Glass Bottles/Containers', 'Glass Bottles/Containers'), ('Aluminum Cans/Containers', 'Aluminum Cans/Containers'), ('E-waste', 'E-waste')], max_length=255)),
                ('lbs', models.FloatField(default=0.0)),
                ('instructions', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='e.g +1 123 234 5678', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Bulk', 'Bulk'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], max_length=100),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.BooleanField(blank=True, default=False, null=True, verbose_name='Remind me when a pickup is scheduled for the following day')),
                ('notify', models.BooleanField(blank=True, default=False, null=True, verbose_name='Notify me when a DoS employee has picked up my bin(s) for a pickup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.IntegerField(choices=[(0, 'Error'), (1, 'Success'), (2, 'Warning'), (3, 'Info')], default=3)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repeat', eventtools.models.ChoiceTextField(blank=True, choices=[('RRULE:FREQ=DAILY', 'Daily'), ('RRULE:FREQ=WEEKLY', 'Weekly'), ('RRULE:FREQ=MONTHLY', 'Monthly'), ('RRULE:FREQ=YEARLY', 'Yearly')], default='')),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PickUpInfo')),
            ],
            options={
                'ordering': ('start', 'end'),
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
