# Generated by Django 3.0.8 on 2020-07-31 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200731_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupinfo',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
