# Generated by Django 3.0.8 on 2020-07-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200731_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='Notify me when a DoS employee has picked up my bin(s) for a pickup'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='reminder',
            field=models.BooleanField(default=False, verbose_name='Remind me when a pickup is scheduled for the following day'),
        ),
    ]
