# Generated by Django 3.0.8 on 2020-08-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200731_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Bulk', 'Bulk'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], default='Individual', max_length=100),
        ),
    ]
