# Generated by Django 3.0.8 on 2020-08-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200731_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
