# Generated by Django 3.0.8 on 2020-08-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersettings_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='customer_id',
            new_name='user',
        ),
    ]
