# Generated by Django 3.0.8 on 2020-08-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200803_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_name',
        ),
    ]
