# Generated by Django 3.0.8 on 2020-08-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_address_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=189),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=189),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=18),
        ),
    ]
