# Generated by Django 3.0.8 on 2020-08-05 02:09

from django.db import migrations, models
import django.db.models.deletion
import eventtools.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_pickupinfo_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupinfo',
            name='owner',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repeat', eventtools.models.ChoiceTextField(blank=True, default='')),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PickUpInfo')),
            ],
            options={
                'ordering': ('start', 'end'),
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Event'),
        ),
    ]
