# Generated by Django 3.0.8 on 2020-08-05 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200804_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='event',
            name='repeat_until',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
    ]
