# Generated by Django 3.0.8 on 2020-08-07 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_completedpickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='seen',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
