# Generated by Django 3.0.8 on 2020-08-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200808_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_name',
            new_name='address_line1',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
